### ISSUE TITLE
更换五子棋博客托管平台 及 与主博客风格一致性

### ISSUE THREAD

**Issue by EthanLin-TWer** [dudulism/linesh-renju-engine#1]
目前Lofter不能满足一些需求，新博客希望有所改善：
- 支持markdown
- 自动截图与自动编号引用
- 更适合摆棋的界面（比如随时可打谱，左右分栏，棋谱相对大小，是否可一行多个图，更有序的棋谱排列等）

**Comment by dudulism** [comment]
All blog related issues are being moved to https://github.com/dudulism/dudulism.github.io/issues/1. Closing this one.
