### ISSUE TITLE
小APP-博客或文章发表时的图片排版

### ISSUE THREAD

**Issue by EthanLin-TWer** [dudulism/linesh-renju-engine#2]
- 四宫格或类似展示形式。需求：有时一个棋背后可能有几种应对，可以同时打出来它们的简单应对，比一句简单的“黑棋17巧妙，白难以应对”更有效，一图胜千言啊。对于水平高的棋手，自己有时可参考；对于水平稍低的棋手，同时给出后续变化简单应对极有帮助
- 能使用支持印刷保真、浏览器端任意放缩的矢量图

**Comment by dudulism** [comment]
All blog related issues are being moved to https://github.com/dudulism/dudulism.github.io/issues/2. Closing this one.
